spring.application.name=veenu-backend
server.port=8081
spring.jpa.open-in-view=false
jwt.secret=veenu-secret-key-change-this-in-production-make-it-long
jwt.expiration=2592000000
resend.api.key=re_KXJyesrA_L79cvowXAzo2Ayyd7VdGGmu8
app.base.url=http://localhost:8081
